global:
  clusterConfig:
    name: ""  # name to identify this cluster for events and metrics
  sysdig:
    accessKey: ""
    accessKeySecret: ""
    secureAPIToken: ""
    secureAPITokenSecret: ""
    region: "us1"
  proxy: {}
  kspm:
    deploy: false
  agentConfigmapName: "sysdig-agent"

agent:
  enabled: true

nodeAnalyzer:
  enabled: true

rapidResponse:
  enabled: false
  rapidResponse:
    passphrase: ""
    existingPassphraseSecret: ""

admissionController:
  enabled: false

